// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cs3/sharing/collaboration/v1beta1/resources.proto

package collaborationv1beta1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/refs/cs3-micro/pkg/cs3/identity/user/v1beta1"
	_ "github.com/refs/cs3-micro/pkg/cs3/storage/provider/v1beta1"
	_ "github.com/refs/cs3-micro/pkg/cs3/types/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package
